[settings]
minimum_release_age = "7d"

[tools]
gcloud = "587.0.0"
"npm:rulesync" = "24.0.0"
terraform = "1.16.4"

[tasks.bootstrap]
run = [
  { task = "rulesync" }
]

[tasks.rulesync]
run = "rulesync generate"
