service_account_id           = "bld-irr-noti-job-dev"
service_account_display_name = "Build Irregular Notification Job (Dev)"
db_name                      = "dotto_dev"
service_name                 = "build-class-change-notifications-job-dev"
schedule                     = "0 13 * * *"
