service_account_id           = "noti-user-job-dev"
service_account_display_name = "Notify User Job (Dev)"
db_name                      = "dotto_dev"
service_name                 = "dispatch-notifications-job-dev"
schedule                     = "30 16 * * *"
